// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Dim4sDU9biqpID2y5IVPEzc04j3BAQU',
    appId: '1:293581091076:web:4f1b1c2e5f6ef2254f6051',
    messagingSenderId: '293581091076',
    projectId: 'mis-recepiesapp-223156-cdc33',
    authDomain: 'mis-recepiesapp-223156-cdc33.firebaseapp.com',
    storageBucket: 'mis-recepiesapp-223156-cdc33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWzlpeUNrloa7ZEYXweVuWorVKgCCtX80',
    appId: '1:293581091076:android:d93b21b0d3c73c664f6051',
    messagingSenderId: '293581091076',
    projectId: 'mis-recepiesapp-223156-cdc33',
    storageBucket: 'mis-recepiesapp-223156-cdc33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqlTPometY2vh9-4rwN8cPz2spiWETZwA',
    appId: '1:293581091076:ios:29719c9445271ff14f6051',
    messagingSenderId: '293581091076',
    projectId: 'mis-recepiesapp-223156-cdc33',
    storageBucket: 'mis-recepiesapp-223156-cdc33.firebasestorage.app',
    iosBundleId: 'com.example.recepiesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqlTPometY2vh9-4rwN8cPz2spiWETZwA',
    appId: '1:293581091076:ios:29719c9445271ff14f6051',
    messagingSenderId: '293581091076',
    projectId: 'mis-recepiesapp-223156-cdc33',
    storageBucket: 'mis-recepiesapp-223156-cdc33.firebasestorage.app',
    iosBundleId: 'com.example.recepiesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Dim4sDU9biqpID2y5IVPEzc04j3BAQU',
    appId: '1:293581091076:web:9e2b155a8bc8c57f4f6051',
    messagingSenderId: '293581091076',
    projectId: 'mis-recepiesapp-223156-cdc33',
    authDomain: 'mis-recepiesapp-223156-cdc33.firebaseapp.com',
    storageBucket: 'mis-recepiesapp-223156-cdc33.firebasestorage.app',
  );
}
